name: threed_viewer
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  archive: ^3.6.1
  desktop_window: ^0.4.2
  file_picker: ^8.1.4
  flutter:
    sdk: flutter
  flutter_inappwebview: ^6.1.5
  flutter_riverpod: ^2.6.1
  freezed: ^2.5.7
  menu_bar: ^0.5.3
  path: ^1.9.0
  path_provider: ^2.1.5
  window_manager: ^0.4.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/html/
    - assets/html/models/
